dist: trusty
sudo: false
services:
- docker
language: go
go:
- 1.9
branches:
  except:
  - "/^\\d+\\.\\d+\\.\\d+-.*\\d+$/"
  - "/\\+travis\\.[0-9]+$/"
env:
  global:
  - ATOMIST_TEAM=T29E48P34
  - secure: rjLSIQW07Z8wRK5HVQndgzreaimEB4lp+Nra7gCdvUkMcZGrNrnGYCBzsSCuC4C+YY9YsDWNtmSjCvy4k3NRf7qfdtnH7kKtwXr1d8wZNiIISW29td1O3hZnXTrsVnW+IYvlq3Ddkgs+FbgEuCQEiPiavpM+ucq6uiO2MKmoAARMPO//sik2JTmPOEQFFBBF+p7p5G3PICTl1Wy1eRKvgxLMEx4Et8nnqlYAeOys+66QtBMaX/50Wn7N5ALYCu3u2k3vuZdyvu91cNjvEpJyWq6gLfC8p/7D+YpjWYZW7BY9IbXDQU8RNNnD9y0chHTB1kvwo5HBGKgNC9ETqSJnMWpBwa8DnLSM2kINI9Ygo6rJyhbxdYBU60NyXPgb4FRY+m/GeqE2esz0C9bNvKCaxKV44t1UEDwYfOJH/V/cC3oxGqd3V3Pg4IorKftfgDMLFaEp8LmAIkcnOjKt0G5f3x/uHw9QH9SNXPemRFOyqBRUR7Ckicuokm5zuNUUGN6FfW9CZ8oWJVKuxtJy5zgbOZi7/oUNfFzHUDhqrGz25RLUQ6GPCWNKFGzu9pwt6WXcLEOUhZoIdjOV0wTq03tDOiCx27IFEMJrLhay4DA5NtkTQTxiEANBZEyIxneaKEXPsaaWUtawZVDtodIa7xbBw9Ct6t3PgoX0ZJGi9oMF8c4=
  - DOCKER_USER=atomistbot
  - secure: barIoIE9mGWklOFd6lCtsQdS/kd5lOnRSHXWIThQPOjQp4bUmnxeOUpc84WWTQPF8wBkvUFHhDcAY1is4SPMx6fsRkeSblgw38942mdIyJDpKDhhuDgBroQB4UZDm5xNcRFPaHYFhr1r3pGIGwG1va54dZJ+s3UfgX81B+9vwj6K3ZJch0ENObzt5Mb+mFrcO7F4fUznClbwLtzupC0SDm4p2FQ+iQtVMYrNzJjyVBlKPK3FOJ9QO0upqkIGRE0ygf+OVgRwx4BFREFzqVlmUeh505pmQhLyPnfwLahRE0SgGI11ZX4McoN+34GMOGU76uJpuASPXo6NBs3l4alihkxEIePNxuycHwV0cIyUrQuRgcXjs96p20E36PqY7Bbk2Q76Y/8H4p6DUfDUkG83j22jfY/03qy3Dv2/Fq7GP3FOq1tuhovSZEItRJvPzFPip47DZf5e7rD4R1QmCKYUYB2w6mTml6hN/pb/yfklmfCFb5AqdQnwz+NH790Ag7eA1GtJTcbfZYyynGRE/FfQesgE+slNJKokF/IIU7SaR0uNHdSR4+o9gcBnVTWCOcI6A7Tbut93madygpKKLgJ5E2mVeh08gSy0OFRCF5GlPh+6PGWObAtrO36NoIIKa7I7rLNZ/pbyj3Zd3mqiIxj2gfwVLaF67Zhm1rELGZRWSIc=
script: bash travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
