---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8vent-serviceaccount
  namespace: k8vent
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8vent-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8vent-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8vent-clusterrole
subjects:
  - kind: ServiceAccount
    name: k8vent-serviceaccount
    namespace: k8vent
