---
apiVersion: v1
kind: Namespace
metadata:
  name: k8vent
  labels:
    owner: atomist
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8vent-serviceaccount
  namespace: k8vent
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8vent-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8vent-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8vent-clusterrole
subjects:
  - kind: ServiceAccount
    name: k8vent-serviceaccount
    namespace: k8vent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8vent
  namespace: k8vent
  labels:
    app: k8vent
    owner: atomist
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: k8vent
      owner: atomist
  template:
    metadata:
      labels:
        app: k8vent
        owner: atomist
        version: '0'
    spec:
      serviceAccountName: k8vent-serviceaccount
      containers:
        - name: k8vent
          image: atomist/k8vent:0.9.0
          env:
            - name: ATOMIST_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: k8vent
                  key: environment
            - name: K8VENT_WEBHOOKS
              valueFrom:
                secretKeyRef:
                  name: k8vent
                  key: webhooks
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
