---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8vent-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: k8vent-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: k8vent-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8vent-role
subjects:
  - kind: ServiceAccount
    name: k8vent-serviceaccount
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8vent
  labels:
    app: k8vent
    owner: atomist
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: k8vent
      owner: atomist
  template:
    metadata:
      labels:
        app: k8vent
        owner: atomist
        version: '0'
    spec:
      serviceAccountName: k8vent-serviceaccount
      containers:
        - name: k8vent
          image: atomist/k8vent:0.8.0
          env:
            - name: ATOMIST_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: k8vent
                  key: environment
            - name: K8VENT_WEBHOOKS
              valueFrom:
                secretKeyRef:
                  name: k8vent
                  key: webhooks
            - name: K8VENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 0.1
              memory: 50Mi
            requests:
              cpu: 0.1
              memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
